// Pokemons - Poke Api
export const FETCH_INIT_POKEMONS = 'FETCH_INIT_POKEMONS';
export const FETCH_POKEMONS_FAILED = 'FETCH_POKEMONS_FAILED';
export const FETCH_POKEMON_DETAILS = 'FETCH_POKEMON_DETAILS';
export const SET_POKEMON_DETAILS = 'SET_POKEMON_DETAILS';
export const SELECTED = 'SELECTED';
export const SET_PREV_PAGE = 'SET_PREV_PAGE';
export const SET_NEXT_PAGE = 'SET_NEXT_PAGE';

// Pokemons Favoritos - Local Data
export const ADD_FAVORITE_POKEMON = 'ADD_FAVORITE_POKEMON';
export const FETCH_FAVORITE_POKEMONS = 'FETCH_FAVORITE_POKEMONS';
export const REMOVE_FAVORITE_POKEMON = 'REMOVE_FAVORITE_POKEMON';
